### PR TITLE
add swift-healthcheck agent plugin

### PR DESCRIPTION
**Pull request by majewsky**

### CODE REVIEW

**Comment by reimannf** [comment]
Very nice work. Could you please add some short notices in the docs/Plugins.md

**Comment by reimannf** [comment]
Move init config to instances, than we could collect info for several domains/openstack backends

**Comment by jobrs** [comment]
Hi colleagues,

my assumption so far was that we would use the Monasca agent user itself for this and have dedicated agent users per service:

Pros:
- password changes or lock-downs of the agent user only affect a single service
- there is only one user to maintain

Cons:
- Cross-monitoring is not possible, i.e. Monasca and Swift must operate in the same region (same KSR)

**Comment by reimannf** [comment]
we wanted to achieve the follwoing:

swift healthcheck for domain 
- cctest_cluster_hcp
- cctest_cluster_3
- ...

This ensures, that a shared service is opeating accross keystone backend boundaries

**Comment by jobrs** [comment]
ok, so you need different check-users for all these domains. got it.

**Pull request merged**
